[workspace]
members = [
    "pallets/clad-token",
    "runtime",
]
resolver = "2"

[workspace.package]
authors = ["Clad Sovereign <helloclad@wideas.tech>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://clad.so"
repository = "https://github.com/clad-sovereign/clad-studio"